- arguments:
  - -XAllowAmbiguousTypes
  - -XApplicativeDo
  - -XBangPatterns
  - -XBlockArguments
  - -XConstraintKinds
  - -XDataKinds
  - -XDeriveAnyClass
  - -XDeriveFoldable
  - -XDeriveFunctor
  - -XDeriveTraversable
  - -XDerivingStrategies
  - -XDerivingVia
  - -XDuplicateRecordFields
  - -XFlexibleContexts
  - -XFlexibleInstances
  - -XFunctionalDependencies
  - -XGADTs
  - -XGeneralisedNewtypeDeriving
  - -XLambdaCase
  - -XMagicHash
  - -XMultiParamTypeClasses
  - -XMultiWayIf
  - -XNamedFieldPuns
  - -XOverloadedStrings
  - -XQuantifiedConstraints
  - -XQuasiQuotes
  - -XPolyKinds
  - -XRankNTypes
  - -XScopedTypeVariables
  - -XStandaloneDeriving
  - -XTemplateHaskell
  - -XTupleSections
  - -XTypeApplications
  - -XTypeFamilies
  - -XTypeOperators
  - -XUndecidableInstances
  - -XViewPatterns
