lib: [
  "_build/install/default/lib/mdx/META"
  "_build/install/default/lib/mdx/block.ml"
  "_build/install/default/lib/mdx/block.mli"
  "_build/install/default/lib/mdx/compat.ml"
  "_build/install/default/lib/mdx/cram.ml"
  "_build/install/default/lib/mdx/cram.mli"
  "_build/install/default/lib/mdx/dune-package"
  "_build/install/default/lib/mdx/lexer.ml"
  "_build/install/default/lib/mdx/lexer_cram.ml"
  "_build/install/default/lib/mdx/lexer_top.ml"
  "_build/install/default/lib/mdx/mdx.a"
  "_build/install/default/lib/mdx/mdx.cma"
  "_build/install/default/lib/mdx/mdx.cmi"
  "_build/install/default/lib/mdx/mdx.cmt"
  "_build/install/default/lib/mdx/mdx.cmti"
  "_build/install/default/lib/mdx/mdx.cmx"
  "_build/install/default/lib/mdx/mdx.cmxa"
  "_build/install/default/lib/mdx/mdx.cmxs"
  "_build/install/default/lib/mdx/mdx.ml"
  "_build/install/default/lib/mdx/mdx.mli"
  "_build/install/default/lib/mdx/mdx__.cmi"
  "_build/install/default/lib/mdx/mdx__.cmt"
  "_build/install/default/lib/mdx/mdx__.cmx"
  "_build/install/default/lib/mdx/mdx__.ml"
  "_build/install/default/lib/mdx/mdx__Block.cmi"
  "_build/install/default/lib/mdx/mdx__Block.cmt"
  "_build/install/default/lib/mdx/mdx__Block.cmti"
  "_build/install/default/lib/mdx/mdx__Block.cmx"
  "_build/install/default/lib/mdx/mdx__Compat.cmi"
  "_build/install/default/lib/mdx/mdx__Compat.cmt"
  "_build/install/default/lib/mdx/mdx__Compat.cmx"
  "_build/install/default/lib/mdx/mdx__Cram.cmi"
  "_build/install/default/lib/mdx/mdx__Cram.cmt"
  "_build/install/default/lib/mdx/mdx__Cram.cmti"
  "_build/install/default/lib/mdx/mdx__Cram.cmx"
  "_build/install/default/lib/mdx/mdx__Lexer.cmi"
  "_build/install/default/lib/mdx/mdx__Lexer.cmt"
  "_build/install/default/lib/mdx/mdx__Lexer.cmx"
  "_build/install/default/lib/mdx/mdx__Lexer_cram.cmi"
  "_build/install/default/lib/mdx/mdx__Lexer_cram.cmt"
  "_build/install/default/lib/mdx/mdx__Lexer_cram.cmx"
  "_build/install/default/lib/mdx/mdx__Lexer_top.cmi"
  "_build/install/default/lib/mdx/mdx__Lexer_top.cmt"
  "_build/install/default/lib/mdx/mdx__Lexer_top.cmx"
  "_build/install/default/lib/mdx/mdx__Migrate_ast.cmi"
  "_build/install/default/lib/mdx/mdx__Migrate_ast.cmt"
  "_build/install/default/lib/mdx/mdx__Migrate_ast.cmx"
  "_build/install/default/lib/mdx/mdx__Misc.cmi"
  "_build/install/default/lib/mdx/mdx__Misc.cmt"
  "_build/install/default/lib/mdx/mdx__Misc.cmx"
  "_build/install/default/lib/mdx/mdx__Output.cmi"
  "_build/install/default/lib/mdx/mdx__Output.cmt"
  "_build/install/default/lib/mdx/mdx__Output.cmti"
  "_build/install/default/lib/mdx/mdx__Output.cmx"
  "_build/install/default/lib/mdx/mdx__Syntax.cmi"
  "_build/install/default/lib/mdx/mdx__Syntax.cmt"
  "_build/install/default/lib/mdx/mdx__Syntax.cmx"
  "_build/install/default/lib/mdx/mdx__Toplevel.cmi"
  "_build/install/default/lib/mdx/mdx__Toplevel.cmt"
  "_build/install/default/lib/mdx/mdx__Toplevel.cmti"
  "_build/install/default/lib/mdx/mdx__Toplevel.cmx"
  "_build/install/default/lib/mdx/migrate_ast.ml"
  "_build/install/default/lib/mdx/misc.ml"
  "_build/install/default/lib/mdx/opam"
  "_build/install/default/lib/mdx/output.ml"
  "_build/install/default/lib/mdx/output.mli"
  "_build/install/default/lib/mdx/syntax.ml"
  "_build/install/default/lib/mdx/top/mdx_top.cma" {"top/mdx_top.cma"}
  "_build/install/default/lib/mdx/top/mdx_top.cmi" {"top/mdx_top.cmi"}
  "_build/install/default/lib/mdx/top/mdx_top.cmt" {"top/mdx_top.cmt"}
  "_build/install/default/lib/mdx/top/mdx_top.cmti" {"top/mdx_top.cmti"}
  "_build/install/default/lib/mdx/top/mdx_top.ml" {"top/mdx_top.ml"}
  "_build/install/default/lib/mdx/top/mdx_top.mli" {"top/mdx_top.mli"}
  "_build/install/default/lib/mdx/top/mdx_top__.cmi" {"top/mdx_top__.cmi"}
  "_build/install/default/lib/mdx/top/mdx_top__.cmt" {"top/mdx_top__.cmt"}
  "_build/install/default/lib/mdx/top/mdx_top__.ml" {"top/mdx_top__.ml"}
  "_build/install/default/lib/mdx/top/mdx_top__Part.cmi" {"top/mdx_top__Part.cmi"}
  "_build/install/default/lib/mdx/top/mdx_top__Part.cmt" {"top/mdx_top__Part.cmt"}
  "_build/install/default/lib/mdx/top/mdx_top__Part.cmti" {"top/mdx_top__Part.cmti"}
  "_build/install/default/lib/mdx/top/part.ml" {"top/part.ml"}
  "_build/install/default/lib/mdx/top/part.mli" {"top/part.mli"}
  "_build/install/default/lib/mdx/toplevel.ml"
  "_build/install/default/lib/mdx/toplevel.mli"
]
bin: [
  "_build/install/default/bin/mdx"
  "_build/install/default/bin/ocaml-mdx"
  "_build/install/default/bin/ocaml-mdx-test"
]
doc: [
  "_build/install/default/doc/mdx/CHANGES.md"
  "_build/install/default/doc/mdx/LICENSE.md"
  "_build/install/default/doc/mdx/README.md"
]
